apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-view-role
  namespace: api
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]
