apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-edit-role
  namespace: api
rules:
- apiGroups: [""]
  resources: ["namespace"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
