apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    deploy: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
        - image: "registryapf4650.azurecr.io/insurance:1.0"
          imagePullPolicy: Always
          name: insurance
          resources:
            limits:
              cpu: "2"
              memory: 4096Mi
            requests:
              cpu: "2"
              memory: 4096Mi
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP