apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: my-container
        image: my-image:latest
        ports:
        - containerPort: 80
