apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer-container
        image: tripviewer-image:latest
        ports:
        - containerPort: 80
         env:
          - name: USERPROFILE_API_ENDPOINT
            valueFrom:
                key: xxx
          - name: TRIPS_API_ENDPOINT
            valueFrom:
                key: xxxx
          - name: BING_MAPS_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: BING_MAPS_KEY
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: my-app
