apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: team7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryapf4650.azurecr.io/tripviewer:latest
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: userprofile-svc.svc.cluster.local:80
          - name: TRIPS_API_ENDPOINT
            value: trips-svc.svc.cluster.local:80
          - name: BING_MAPS_KEY
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: BING_MAPS_KEY
