apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer-container
        image: tripviewer-image:latest
        ports:
        - containerPort: 80
