apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - name: userjava
        image: registryapf4650.azurecr.io/user-java:latest
        volumeMounts:
        - name: secrets-volume
          mountPath: "/secrets"
          readOnly: true
        ports:
        - containerPort: 80
        env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: SQL_DBNAME
      volumes:
      - name: secrets-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"
