apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: tripviewer
