apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-view-rolebinding
  namespace: web
subjects:
- kind: User
  name: web-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: api-view-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-edit-rolebinding
  namespace: api
subjects:
- kind: User
  name: web-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: web-edit-role
  apiGroup: rbac.authorization.k8s.io
